### ISSUE TITLE
Unresolved Dependency Causes StackTrace

### ISSUE THREAD

**Issue by darkn3rd** [chef/knife-google#127]
# Version:

* `knife-google (3.2.0)`
* `google-cloud-sdk: 197.0.0-0`
* Ubuntu 16.04 Xenial
* ChefDK
  ```
  Chef Development Kit Version: 2.3.5
  chef-client version: 13.4.19
  delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
  berks version: 6.3.1
  kitchen version: 1.17.0
  inspec version: 1.39.1
  ```

# Scenario:

I am trying to install and use knife google, just list servers.

# Steps to Reproduce:

1. `chef gem install knife-google`
2. `knife google server list`

# Expected Result:

List of servers, Not Crashing

# Actual Result:

Crashing, stack trace.  Looks like unresolved dependency that was expected to be there, but specified in Gemfile.

```
/opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:2293:in `raise_if_conflicts': Unable to activate knife-google-3.2.0, because google-api-client-0.8.7 conflicts with google-api-client (~> 0.9.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/joaquin/.chefdk/gem/ruby/2.4.0/gems/knife-google-3.2.0/lib/chef/knife/google_zone_list.rb:22:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:267:in `load'
	from /opt/chefdk/bin/knife:267:in `<main>'
```

**Comment by darkn3rd** [comment]
Workaround, downloaded and installed ChefDK 2.5.3, which installs ` google-api-client 0.9.28`  Recommend installing required gems (avoid works on my laptop situation).

**Comment by tas50** [comment]
We've bumped this dep in the latest ChefDK. You'll want to update to DK 3.3 and this should go away.
