### ISSUE TITLE
knife google server create fails while bootstrap to centos node

### ISSUE THREAD

**Issue by NAshwini** [chef/knife-google#144]
# Version:

knife-google v3.3.7 and chef v15.0.238 on workstation

# Environment:

centos-7

# Scenario:

`knife google server create ash-instance-3 --gce-image centos-7-v20160219 --gce-machine-type n1-standard-1 --gce-public-ip ephemeral --ssh-user msys --identity-file C:\Users\msys\.ssh\id_rsa --gce_project "ash-account-project" --gce_zone "us-east1-c" -c "D:\chef-repo\.chef\knife.rb" --image-os-type linux --bootstrap-protocol ssh -VV`

# Steps to Reproduce:

Please run above command to create the node from workstation.

# Expected Result:

It should create the instance in google account and bootstrap the node.

# Actual Result:

It create the instance in google account but fails to bootstrap the node by below error:
`FATAL: Check if --bootstrap-protocol and --image-os-type is correct. uninitialized constant Chef::Knife::Bootstrap::ClientBuilder
       Did you mean?  Chef::Knife::ClientBulkDelete`

# Stacktrace

``` 
Traceback (most recent call last):
        16: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
        15: from C:/opscode/chef/embedded/bin/knife:23:in `load'
        14: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/bin/knife:24:in `<top (required)>'
        13: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        12: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:221:in `run'
        11: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/command.rb:53:in `run'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:79:in `after_exec_command'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:104:in `bootstrap'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/bootstrapper.rb:39:in `bootstrap'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/bootstrapper.rb:51:in `create_bootstrap_protocol'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/bootstrapper.rb:51:in `new'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/ssh_bootstrap_protocol.rb:30:in `initialize'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/ssh_bootstrap_protocol.rb:30:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife/bootstrap.rb:401:in `initialize': uninitialized constant Chef::Knife::Bootstrap::ClientBuilder (NameError)
Did you mean?  Chef::Knife::ClientBulkDelete
        10: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
         9: from C:/opscode/chef/embedded/bin/knife:23:in `load'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/bin/knife:24:in `<top (required)>'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:221:in `run'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238-universal-mingw32/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/command.rb:53:in `run'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:77:in `after_exec_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:88:in `rescue in after_exec_command': Check if --bootstrap-protocol and --image-os-type is correct. uninitialized constant Chef::Knife::Bootstrap::ClientBuilder (NameError)
Did you mean?  Chef::Knife::ClientBulkDelete 
```

**Comment by NAshwini** [comment]
I tried with `--connection-protocol` instead of `--bootstrap-protocol` as per https://github.com/chef/chef/blob/master/RELEASE_NOTES.md but in this case its says `Error: invalid option: --connection-protocol`

**Comment by NAshwini** [comment]
This issue will be resolve by PR : https://github.com/chef/knife-windows/pull/480
