### ISSUE TITLE
knife google server create fails for option --bootstrap-protocol and --image-os-type

### ISSUE THREAD

**Issue by NAshwini** [chef/knife-google#145]
# Version:
knife-google v3.3.7 and chef v15.0.266 on workstation

# Environment:

centos-7

# Scenario:

```knife google server create ash-instance-3 --gce-image centos-7-v20160219 --gce-machine-type n1-standard-1 --gce-public-ip ephemeral --ssh-user msys --identity-file C:\Users\msys\.ssh\id_rsa --gce_project "ash-account-project" --gce_zone "us-east1-c" -c "D:\chef-repo\.chef\knife.rb" --image-os-type linux --bootstrap-protocol ssh -VV```

# Steps to Reproduce:

Please run above command to create the node from workstation.

# Expected Result:

It should create the instance in google account and bootstrap the node.

# Actual Result:

It create the instance in google account but fails to bootstrap the node by below error: 
```FATAL: Check if --bootstrap-protocol and --image-os-type is correct. undefined method `include?' for nil:NilClass```

# Stacktrace

```
FATAL: Check if --bootstrap-protocol and --image-os-type is correct. undefined method `include?' for nil:NilClass
Traceback (most recent call last):
        17: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
        16: from C:/opscode/chef/embedded/bin/knife:23:in `load'
        15: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/bin/knife:24:in `<top (required)>'
        14: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
        13: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:221:in `run'
        12: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
        11: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
        10: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:467:in `block in run_with_pretty_exceptions'
         9: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/command.rb:53:in `run'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:81:in `after_exec_command'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:106:in `bootstrap'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/bootstrapper.rb:42:in `bootstrap'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/chefbootstrap/bootstrap_protocol.rb:44:in `send_bootstrap_command'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:526:in `run'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:660:in `verify_deprecated_flags!'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:660:in `each'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife/bootstrap.rb:662:in `block in verify_deprecated_flags!'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:378:in `config_source': undefined method `include?' for nil:NilClass (NoMethodError)
        10: from C:/opscode/chef/embedded/bin/knife:23:in `<main>'
         9: from C:/opscode/chef/embedded/bin/knife:23:in `load'
         8: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/bin/knife:24:in `<top (required)>'
         7: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/application/knife.rb:162:in `run'
         6: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:221:in `run'
         5: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
         4: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/local_mode.rb:41:in `with_server_connectivity'
         3: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb:467:in `block in run_with_pretty_exceptions'
         2: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/command.rb:53:in `run'
         1: from C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:79:in `after_exec_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:90:in `rescue in after_exec_command': Check if --bootstrap-protocol and --image-os-type is correct. undefined method `include?' for nil:NilClass (NoMethodError)
```

**Comment by NAshwini** [comment]
Its giving error for `host_key_verify` 
# stacktrace
``` 
[375, 384] in C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.266-universal-mingw32/lib/chef/knife.rb
   375:     #   - :config - this came from Chef::Config[:knife]
   376:     #   - :cli_default - came from a declared CLI `option`'s `default` value.
   377:     #   - nil - if they key does not exist
   378:     def config_source(key)
   379:       byebug
=> 380:       return :cli if @original_config.include? key
   381:       return :config if config_file_settings.key? key
   382:       return :cli_default if default_config.include? key
   383:       nil
   384:     end
(byebug) key
:host_key_verify
(byebug) @original_config.include? key
*** NoMethodError Exception: undefined method `include?' for nil:NilClass
```

**Comment by NAshwini** [comment]
With reference to this PR chef/chef#8494, This issue will be resolved by PR: https://github.com/chef/chef/pull/8506
