### ISSUE TITLE
ssh-agent no key added issue while node bootstra.

### ISSUE THREAD

**Issue by NAshwini** [chef/knife-google#146]
# Version:

knife-google v3.3.7 and chef v15.0.266 on workstation

# Environment:

centos-7

# Scenario:

``` knife google server create ash-instance-3 --gce-image centos-7-v20160219 --gce-machine-type n1-standard-1 --gce-public-ip ephemeral --ssh-user msys --identity-file C:\Users\msys\.ssh\id_rsa --gce_project "ash-account-project" --gce_zone "us-east1-c" -c "D:\chef-repo\.chef\knife.rb" --image-os-type linux --bootstrap-protocol ssh -VV ```

# Steps to Reproduce:

Please run above command to create the node from workstation.

# Expected Result:

It should create the instance in google account and bootstrap the node.

# Actual Result:

It create the instance in google account but fails to bootstrap the node by below error: ``` command.rb:79:in `after_exec_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:90:in `rescue in after_exec_command': Check if --bootstrap-protocol and --image-os-type is correct. Your SSH Agent has no keys added, and you have not specified a password or a key file (Train::ClientError) ```

**Comment by NAshwini** [comment]
I have added the key `C:\Users\msys\.ssh\id_rsa` to my ssh-agent but still I am facing the same issue.
This is issue can be fixed by fixing the issue https://github.com/chef/chef/issues/8493
