### ISSUE TITLE
google-knife and knife dependency versions

### ISSUE THREAD

**Issue by reprogrammer** [chef/knife-google#43]
After I install google-knife, knife fails to run any commands, because of several gem conflict errors. What would you recommend to satisfy the dependency requirements of both knife and knife-google?

The following is a sequence of bash commands that reproduces the problem.

**`cat /etc/*-release`**
```
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)
```
**`wget https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chefdk-0.3.5-1.x86_64.rpm`**
**`rpm -Uvh chefdk-0.3.5-1.x86_64.rpm`**
**`knife help node`**
**`chef gem install knife-google`**
```
Fetching: retriable-1.4.1.gem (100%)
WARNING:  You don't have /root/.chefdk/gem/ruby/2.1.0/bin in your PATH,
          gem executables will not run.
Successfully installed retriable-1.4.1
Fetching: launchy-2.4.3.gem (100%)
Successfully installed launchy-2.4.3
Fetching: extlib-0.9.16.gem (100%)
Successfully installed extlib-0.9.16
Fetching: autoparse-0.3.3.gem (100%)
Successfully installed autoparse-0.3.3
Fetching: jwt-1.2.0.gem (100%)
Successfully installed jwt-1.2.0
Fetching: signet-0.6.0.gem (100%)
Successfully installed signet-0.6.0
Fetching: google-api-client-0.8.2.gem (100%)
Successfully installed google-api-client-0.8.2
Fetching: knife-google-1.3.1.gem (100%)
Successfully installed knife-google-1.3.1
Parsing documentation for retriable-1.4.1
Installing ri documentation for retriable-1.4.1
Parsing documentation for launchy-2.4.3
Installing ri documentation for launchy-2.4.3
Parsing documentation for extlib-0.9.16
Installing ri documentation for extlib-0.9.16
Parsing documentation for autoparse-0.3.3
Installing ri documentation for autoparse-0.3.3
Parsing documentation for jwt-1.2.0
Installing ri documentation for jwt-1.2.0
Parsing documentation for signet-0.6.0
Installing ri documentation for signet-0.6.0
Parsing documentation for google-api-client-0.8.2
Installing ri documentation for google-api-client-0.8.2
Parsing documentation for knife-google-1.3.1
Installing ri documentation for knife-google-1.3.1
Done installing documentation for retriable, launchy, extlib, autoparse, jwt, signet, google-api-client, knife-google afte
r 7 seconds
8 gems installed
```
**`knife help node`**
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2099:in `raise_if_conflicts': Unable to activate chef-11.6.2, because mixlib-config-2.1.0 conflict
s with mixlib-config (>= 1.1.2, ~> 1.1), ohai-7.4.0 conflicts with ohai (< 7.0.0, >= 0.6.0), json-1.8.1 conflicts with json (<= 1.7.7, >= 1.4.4), net-ssh-multi-1.2.0 conf
licts with net-ssh-multi (~> 1.1.0) (Gem::ConflictError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:90:in `block in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in `each'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/google-api-client-0.8.2/lib/google/api_client/auth/storages/redis_store.rb:15:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/google-api-client-0.8.2/lib/google/api_client/service_account.rb:20:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/google-api-client-0.8.2/lib/google/api_client.rb:31:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/google/compute/client.rb:17:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/google/compute.rb:29:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /root/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/chef/knife/google_base.rb:16:in `<top (required)>'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `load'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `block in load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `each'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:120:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:168:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:33:in `load'
        from /usr/bin/knife:33:in `<main>'
```
**`chef gem uninstall knife-google`**
```
Successfully uninstalled knife-google-1.3.1
```
**`knife help node`**

**Comment by Zhomart** [comment]
I could fix this by `$ chef gem update --no-ri --no-rdoc`

**Comment by paulrossman** [comment]
My suggestion is to update to knife-google 1.4.x. There were a bunch of dependency changes in #54.

Closing this issue due to age. If the issue still persists, please open a new issue with details.
