### ISSUE TITLE
knife-google fails with google-api-client >0.8

### ISSUE THREAD

**Issue by zenitraM** [chef/knife-google#44]
```
knife google zone list -VV
/Users/zenitram/.chefdk/gem/ruby/2.1.0/gems/google-api-client-0.8.2/lib/google/api_client/environment.rb:26: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/zenitram/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/google/compute/resource_collection.rb:69:in `api_resource': undefined method `snake_case' for "Zone":String (NoMethodError)
	from /Users/zenitram/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/google/compute/listable_resource_collection.rb:22:in `list'
	from /Users/zenitram/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.3.1/lib/chef/knife/google_zone_list.rb:37:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:33:in `load'
	from /usr/bin/knife:33:in `<main>'
```
Using chef-dk with latest knife-google gem. Downgrading to google-api-client 0.7.1 made everything work again..

**Comment by erjohnso** [comment]
Thanks for the report @zenitraM and the workaround until this can get fixed.

**Comment by samklr** [comment]
Hi @zenitraM How do you downgrade to google-api-0.7.1 ? Thanks

**Comment by zenitraM** [comment]
@samkir you can do something like:
```
gem install google-api -V 0.7.1
gem uninstall google-api
```
and then choose to uninstall the newer version

**Comment by paulrossman** [comment]
#51 compatible with latest 'google-api-client' that requires 'extlib'. Fixes 'snake_case'.
