### ISSUE TITLE
Dependency conflict building from master

### ISSUE THREAD

**Issue by nckturner** [chef/knife-google#65]
Fresh install of chefdk on ubuntu 14.04 gives me this error: 

```
chef@chef00-mgmt:~/knife-google⟫ /opt/chefdk/embedded/bin/gem install knife-google-1.4.3.gem
WARNING:  You don't have /home/chef/.chefdk/gem/ruby/2.1.0/bin in your PATH,
          gem executables will not run.
Successfully installed knife-google-1.4.3
1 gem installed
chef@chef00-mgmt:~/knife-google⟫ knife google
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate googleauth-0.4.1, because logging-1.8.2 conflicts with logging (~> 2.0) (Gem::ConflictError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/chef/.chefdk/gem/ruby/2.1.0/gems/knife-google-1.4.3/lib/chef/knife/google_base.rb:16:in `<top (required)>'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:127:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:208:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
        from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:51:in `load'
        from /usr/bin/knife:51:in `<main>'
```

Thanks for any help you can provide!

**Comment by yonah-codefresh** [comment]
+1

**Comment by yonah-codefresh** [comment]
I got past this by upgrading chef-dk from 0.6.2 to 0.7.0 and uninstalling knife-windows
fyi

**Comment by siddheshwar-more** [comment]
@nckturner @yonah-codefresh 
We are looking into this!

**Comment by siddheshwar-more** [comment]
@nckturner 
The `logging` gem conflict for `winrm` gem is due to https://github.com/WinRb/WinRM/blob/v1.3.3/winrm.gemspec#L34 

Workaround for now is -

Open below file -
`sudo vim /opt/chefdk/embedded/lib/ruby/gems/2.1.0/specifications/winrm-1.3.3.gemspec`

and replace all references of `s.add_dependency(%q<logging>, [">= 1.6.1","~>1.6"])` by  `s.add_dependency(%q<logging>, [">= 1.6.1"])`

We will fix this in next release !

Thank You!

**Comment by nckturner** [comment]
Thanks I'll try it out

**Comment by siddheshwar-more** [comment]
@nckturner - 
FYI-
I've created issue at WinRM gem - https://github.com/WinRb/WinRM/issues/147 

Thank you for reporting this!

**Comment by adamleff** [comment]
Closing out this old issue. This should no longer be an issue with newer winrm, google-api-client, and googleauth gems. Thanks!
